version: "3.9"

x-general: &general
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_HOSTNAME: mysql
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: test_db

x-mysql: &mysql
  MYSQL_ROOT_PASSWORD: root

services:
  app:
    build: ./app/.
    ports:
      - 80:8080
    restart: always
    environment:
      <<: *general

  db:
    image: mysql:8.0.23
    restart: always
    environment:
      <<: *general
      <<: *mysql
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql


  adminer:
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - 8888:8080

volumes:
  db:
