version: "3.9"

x-general: &general
  POSTGRES_PASSWORD: password
  POSTGRES_USER: user
  POSTGRES_DB: test_db

services:
  app:
    build: ./app/.
    ports:
      - 80:8080
    restart: always
    environment:
      <<: *general

  db:
    image: postgres:14.0
    restart: always
    environment:
      <<: *general
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data


  adminer:
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - 8888:8080

volumes:
  db:
